# ConfigMap: Provides Filebeat configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"]
---
# Pod: Runs Nginx and Filebeat side by side
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  # NGINX web server
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx/
  # Filebeat log shipper
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumeMounts:
    # Mount the config file from ConfigMap with subPath
    - name: filebeat-config
      mountPath: /usr/share/filebeat/filebeat.yml
      subPath: filebeat.yml
    # Mount the shared log volume to read Nginx logs
    - name: nginx-logs
      mountPath: /var/log/nginx/

  # Shared volumes between containers      
  volumes:
  # Shared log volume where Nginx writes logs and Filebeat reads them
  - name: nginx-logs
    emptyDir: {}
  # Mount the filebeat.yml config from the ConfigMap
  - name: filebeat-config
    configMap:
      name: filebeat
      items:
        - key: filebeat.yml
          path: filebeat.yml