# ConfigMap: Provides Filebeat configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true

    filebeat.modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]

    output:
      elasticsearch:
        hosts: ["http://elasticsearch:9200"]

    setup:
      ilm:
        enabled: false
      index: "filebeat-nginx-%{+yyyy.MM.dd}"

---
# Pod: Runs Nginx and Filebeat side by side
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-filebeat
spec:
  containers:
    # NGINX web server
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"

    # Filebeat log shipper
    - name: filebeat
      image: docker.elastic.co/beats/filebeat:7.5.0
      # Sleep briefly before starting Filebeat to allow Nginx logs to be created
      command: ["/bin/sh", "-c"]
      args:
        - "sleep 10 && filebeat -e -c /usr/share/filebeat/filebeat.yml --strict.perms=false"
      volumeMounts:
        # Mount the config file from ConfigMap with subPath
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        # Mount the shared log volume to read Nginx logs
        - name: nginx-logs
          mountPath: /var/log/nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"

  # Shared volumes between containers
  volumes:
    # Shared log volume where Nginx writes logs and Filebeat reads them
    - name: nginx-logs
      emptyDir: {}
    # Mount the filebeat.yml config from the ConfigMap
    - name: filebeat-config
      configMap:
        name: filebeat
        items:
          - key: filebeat.yml
            path: filebeat.yml











# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: filebeat
# data:
#   filebeat.yml: |
#     filebeat:
#       config:
#         modules:
#           path: /usr/share/filebeat/modules.d/*.yml
#           reload:
#             enabled: true
#       modules:
#       - module: nginx
#         access:
#           var.paths: ["/var/log/nginx/access.log*"]
#         error:
#           var.paths: ["/var/log/nginx/error.log*"]
#     output:
#       elasticsearch:
#         hosts: ["elasticsearch:9200"]
# ---
# kind: Pod
# apiVersion: v1
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: nginx-logs
#       mountPath: /var/log/nginx/
#   - name: filebeat
#     image: docker.elastic.co/beats/filebeat:7.5.0
#     volumeMounts:
#     - name: filebeat-config
#       mountPath: /usr/share/filebeat/filebeat.yml
#       subPath: filebeat.yml
#     - name: nginx-logs
#       mountPath: /var/log/nginx/
#   volumes:
#   - name: nginx-logs
#     emptyDir: {}
#   - name: filebeat-config
#     configMap:
#       name: filebeat
#       items:
#         - key: filebeat.yml
#           path: filebeat.yml