apiVersion: v1
kind: Pod
metadata:
  name: emptydirdemo
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:                                    
      - name: xchange               
        mountPath: "/tmp/nginxContainer"    
          
  - name: jenkins-container
    image: jenkins:2.60.3
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: xchange               
        mountPath: "/tmp/jenkinsContainer"      
  volumes:                                                  
  - name: xchange                   
    emptyDir: {} 
