apiVersion: v1
kind: Pod
metadata:
  name: hostpathdemo
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: testvolume  # Refers to the volume defined below
          mountPath: /tmp/nginxContainer
  volumes:
    - name: testvolume
      hostPath:
        path: /tmp/data  # Directory on the host node
        type: DirectoryOrCreate # Creates the directory if it doesn't exist